chemputation: main.o chemputation.o
        g++ main.o chemputation.o -o chemputation

main.o: main.cpp
        g++ -c main.cpp

chemputation.o: chemputation.cpp
        g++ -c chemputation.cpp

clean:
        rm *.o chemputation
